name: Deploy Push

on:
  workflow_dispatch:
    inputs:
      app:
        required: true
        type: string
        options:
          - 'lab'
          - 'web'
          - 'admin'
          - 'store'

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          
      - name: Create and switch to deploy branch
        run: |
          DEPLOY_BRANCH="deploy/${{ github.event.inputs.app }}"
          git checkout -b $DEPLOY_BRANCH
          
      - name: Stage changes
        run: |
          git add .
          
      - name: Commit changes
        run: |
          git commit -m "Deploy ${{ github.event.inputs.app }} - Triggered by workflow_dispatch"
          
      - name: Push to deploy branch
        run: |
          git push origin "deploy/${{ github.event.inputs.app }}" --force